apiVersion: v1
kind: Pod
metadata:
  labels:
    app: multi-cont-pod-shared-volume
  name: multi-cont-pod
spec:
  volumes:
  - name: var-logs
    emptyDir: {}
  containers:
  - name: sidecar-container
    image: busybox
    command: ["bin/sh", "-c", "echo Hello, I am from Sidecar Container >> /var/log/index.html"]
    volumeMounts:
    - name: var-logs
      mountPath: /var/log
  - name: main-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: var-logs
      mountPath: /usr/share/nginx/html
  #restartPolicy: OnFailure