apiVersion: v1
kind: Pod
metadata:
    name: nodejs-app
    labels:
        app: nodejs-app
spec:
    containers:
    - name: nodejs-app
      image: node-app
      ports:
      - containerPort: 8080
      imagePullPolicy: Never