apiVersion: v1
kind: ReplicationController
metadata:
    name: nodejs-replication-controller
spec:
    replicas: 3
    selector:
        app: nodejs-app-selector
    template:
        metadata:
            labels:
                app: nodejs-app-selector
        spec:
            containers:
              - name: nodejs-app-container
                image: node-app
                ports:
                    - containerPort: 8080
                imagePullPolicy: Never
    