apiVersion: v1
kind: Pod
metadata:
    name: nodejs-healthcheck
    labels:
        app: nodejs-app
spec:
    containers:
        - name: nodejs-app
          image: node-app
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
                path: /
                port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 30