apiVersion: apps/v1
kind: Deployment
metadata:
    name: nodejs-deployment-healthcheck
spec:
    replicas: 3
    selector:
        matchLabels: 
            app: nodejs-app-selector
    template:
        metadata:
            labels:
                app: nodejs-app-selector
        spec:
            containers:
              - name: nodejs-app-container
                image: node-app
                ports:
                    - name: nodejs-port
                      containerPort: 8080
                imagePullPolicy: Never
                livenessProbe:
                    httpGet:
                        path: /
                        port: nodejs-port
                    initialDelaySeconds: 10
                    timeoutSeconds: 30