apiVersion: apps/v1
kind: Deployment
metadata:
    name: nodejs-deployment-secrets
spec:
    selector:
        matchLabels: 
            app: nodejs-app
    template:
        metadata:
            labels:
                app: nodejs-app
        spec:
            containers:
                - name: nodejs-app
                  image: node-app
                  ports:
                    - containerPort: 8080
                  imagePullPolicy: Never
                  env:
                    - name: DB_USERNAME
                      valueFrom:
                        secretKeyRef:
                            name: db-credentials
                            key: username
                    - name: DB_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: db-credentials
                            key: password