apiVersion: apps/v1
kind: Deployment
metadata:
    name: nodejs-deployment-secrets
spec:
    selector:
        matchLabels: 
            app: nodejs-app
    template:
        metadata:
            labels:
                app: nodejs-app
        spec:
            containers:
                - name: nodejs-app
                  image: node-app
                  ports:
                    - containerPort: 8080
                  imagePullPolicy: Never
                  volumeMounts:
                    - name: db-cred-volume
                      mountPath: /etc/creds
                      readOnly: true
            volumes:
              - name: db-cred-volume
                secret:
                    secretName: db-credentials