apiVersion: v1
kind: Pod
metadata:
    name: nodejs-app
    labels:
        app: nodejs-app
spec:
    containers:
    - name: nodejs-app
      image: node-app
      ports:
      - containerPort: 8080
      imagePullPolicy: Never
      resources:
        requests:
            cpu: 50m
            memory: 256Mi
        limits:
            cpu: 100m
            memory: 512Mi